[package]
name = "sort-order-poc"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[features]
icu = ["dep:icu_collator", "dep:icu_locale_core"]

[dependencies]
icu_collator = { version = "2.3", optional = true }
icu_locale_core = { version = "2", optional = true }

[[bin]]
name = "simple"
path = "src/bin/simple.rs"

[[bin]]
name = "icu"
path = "src/bin/icu.rs"
required-features = ["icu"]

[profile.release]
strip = true
