[package]
name = "semoxide-schema"
description = "semoxide.toml configuration types and JSON Schema generation."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
semoxide-error.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
toml.workspace = true

[dev-dependencies]
rstest.workspace = true
